Timeline section
daybreak-studio/superpower pull request #16
Opened 2024-04-17 20:09 UTC by alvinleung

- Merged with scrolling text section branch, and testimonial section branch, but testimonial section probably has some changes in the version history
- Implemented responsive 3d timeline based on @kiranpate1 prototype

2024-04-17 23:40 UTC, christopher-ha requested changes
@alvinleung @kiranpate1 Good refactor for the timeline section. 

@kiranpate1 for the Scrolling Text section, it looks great but needs some refactoring for performance.

Scrolling text section could refactor some logic on the scrollProgress tracking, the way it's coded right now works, but there are hooks with Framer Motion that handle that scrollProgress tracking for you. 

Scrolling text has perf bottleneck with each span triggering an opacity blur re-render on each scroll event. Either throttle scroll so it triggers less often at a larger step count, or batch the blur by triggering blur on each word instead of each character. This will reduce the amount of animations from 161 char to 26 words.

(Minor) Scrolling text has responsive issue for tablet (height: svh) but this can be fixed later when we do tablet styling.

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +    const section = document.querySelector(".relative.h-svh") as HTMLElement;
useRef instead of document.querySelector

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +      const scrollProgress =
Use Framer motion useScroll / scrollYProgress hook for this as its more performant.

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +    } else if (scrollPosition < sectionTop - viewportCenter) {
Looks like you're trying to grab the specific scroll progress based on the div container.

Use Framer Motion useScroll with a container reference, this will output a motion value for you that will only track that div. 

Resource: https://www.framer.com/motion/use-scroll/#%23element-scroll

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +    return () => window.removeEventListener("scroll", handleScroll);
Same as above, you could remove all of this logic and replace it with useScroll

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +                <motion.span
Good logic here for the animation but for performance we should change this to trigger on each word instead of every letter. It should be simple change as you are already splitting up the sentence by each word.

2024-04-17 23:40 UTC, christopher-ha commented on components/Sections/TimelineSection/Waypoint.tsx
> +    <path d="M1.5 1L5.5 5L1.5 9" stroke="#FE8000" stroke-width="2" />
(Minor)

Change this to strokeWidth. This threw a large warning in local deployment.

"Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?"

2024-04-26 17:22 UTC, daybreakstud1o commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +    const section = document.querySelector(".relative.h-svh") as HTMLElement;
addressed!

2024-04-26 17:22 UTC, daybreakstud1o commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +      const scrollProgress =
Refactored in the latest update

2024-04-26 17:23 UTC, daybreakstud1o commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +    } else if (scrollPosition < sectionTop - viewportCenter) {
Refactored in the latest update

2024-04-26 17:23 UTC, daybreakstud1o commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +                <motion.span
Refactored in the latest update

2024-04-26 17:24 UTC, daybreakstud1o commented on components/Sections/TimelineSection/Waypoint.tsx
> +    <path d="M1.5 1L5.5 5L1.5 9" stroke="#FE8000" stroke-width="2" />
fixed!

2024-04-26 17:33 UTC, daybreakstud1o commented
Added 2 extra useful hooks

## useMotionValueSwitch

```tsx

const { scrollYProgress } = useScroll();

// A state that that switches on/off based on the condition function
const shouldShowButton = useMotionValueSwitch(scrollYProgress,
   (latest) => latest > 1 
);

```

## useLogMotionValue

```
// log motion value changes
const { scrollYProgress } = useScroll(); 
useLogMotionValue(scrollYProgress, "scrollYProgress");
```

## useItemTransitionProgress
Extract transition progress(MotionValue) of an item from a collection, with reference to an overall motion value that depicts the overall progress. Particularly useful for building scroll interaction that involves a series of item.

```tsx

const GalleryItem = ({index, totalPhotosCount, sectionScrollProgress})=> {
  const animProgress = useItemTransitionProgress({
     index, 
     total:totalPhotosCount, 
     progress: sectionScrollProgress
     // optional - should the transition value exceed the range of [-1,1]
     clamp: false,
     // optional - the transition in and out occupies 0.2 progress separately  
     durationProgress: .2
  });
}
```

2024-04-26 20:02 UTC, christopher-ha approved these changes
Great refactor. The performance issue for the blurred text is also fixed since we are now iterating over each word instead of every letter. Hooks are incredibly useful, especially the useLogMotionValue which uses useMotionValueEvent under the hood. 

Approved.

2024-04-26 20:02 UTC, christopher-ha commented on components/Sections/ScrollingTextSection/ScrollingTextLayout.tsx
> +  const wordCount = sentenceArray.length;
Good change from letter count to word count.

2024-04-26 20:03 UTC, merged